name: Linux Terminal
on: [workflow_dispatch]
jobs:
  terminal:
    runs-on: ubuntu-latest
    steps:
      - name: Start interactive shell
        run: |
          echo "Terminal Linux ativo por 30 minutos (use 'exit' para sair)"
          bash -i
        timeout-minutes: 30
